#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task App', '0.1');

try {
   $pdo = new PDO('sqlite:db.sqlite');
   
   $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
   $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
   
} catch (Exception $exception) {
   echo 'Could not connect to the database';
   exit(1);
}

$dbAdapter = new hotsaucejake\DatabaseAdapter($pdo);

$app->add(new hotsaucejake\ShowCommand($dbAdapter));
$app->add(new hotsaucejake\AddCommand($dbAdapter));
$app->add(new hotsaucejake\CompleteCommand($dbAdapter));

$app->run();